# Generated by Django 5.2.4 on 2025-07-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyiha1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mahalla',
            options={'ordering': ['-created_at'], 'verbose_name': 'Mahalla', 'verbose_name_plural': 'MAHALLALAR'},
        ),
        migrations.AddField(
            model_name='mahalla',
            name='is_bool',
            field=models.BooleanField(default=True),
        ),
    ]
