# Generated by Django 5.2.4 on 2025-07-16 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyiha1', '0002_alter_mahalla_options_mahalla_is_bool'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tuman',
            options={'ordering': ['-created_at'], 'verbose_name': 'Tuman', 'verbose_name_plural': 'TUMANLAR'},
        ),
        migrations.AddField(
            model_name='tuman',
            name='is_bool',
            field=models.BooleanField(default=True),
        ),
    ]
