# Generated by Django 5.2.4 on 2025-07-16 20:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyiha1', '0003_alter_tuman_options_tuman_is_bool'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viloyat',
            options={'ordering': ['-created_at'], 'verbose_name': 'Viloyat', 'verbose_name_plural': 'VILOYATLAR'},
        ),
        migrations.AddField(
            model_name='viloyat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='viloyat',
            name='is_bool',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='viloyat',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
